spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: movie-catalog-service
              uri: lb://movie-catalog-service
              predicates:
                - Path=/catalog/**
              filters:
                - StripPrefix=1

filters:
  - name: CircuitBreaker
    args:
      name: catalogCB
      fallbackUri: forward:/fallback/catalog
  - name: RequestRateLimiter
    args:
      redis-rate-limiter.replenishRate: 10
      redis-rate-limiter.burstCapacity: 20

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"

